# Generated by Django 2.0.7 on 2018-07-17 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='the name of the city', max_length=64, verbose_name='name')),
                ('denonym', models.CharField(blank=True, help_text='the denonym of the city', max_length=64, verbose_name='denonym')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='the name of the continent', max_length=64, verbose_name='name')),
                ('denonym', models.CharField(blank=True, help_text='the denonym of the continent', max_length=64, verbose_name='denonym')),
                ('code', models.CharField(help_text='the code of the continent', max_length=2, unique=True, verbose_name='code')),
            ],
            options={
                'verbose_name': 'continent',
                'verbose_name_plural': 'continents',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='the name of the country', max_length=64, verbose_name='name')),
                ('denonym', models.CharField(blank=True, help_text='the denonym of the country', max_length=64, verbose_name='denonym')),
                ('code', models.CharField(help_text='the code of the country', max_length=2, unique=True, verbose_name='code')),
                ('continent', models.ForeignKey(help_text='the continent of the country', on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='sample.Continent', verbose_name='continent')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(help_text='the country of the city', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='sample.Country', verbose_name='country'),
        ),
    ]
