# Generated by Django 2.0 on 2018-08-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.IntegerField(help_text='the area of the geo', verbose_name='area')),
            ],
            options={
                'verbose_name': 'geo',
                'verbose_name_plural': 'geos',
            },
        ),
    ]
